### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by betsythefc** [ello/ello-android#37]
Can we have the ello-android app submitted to the F-Droid app store for those of us that do not rely on the Google Play Store?

https://f-droid.org/contribute/

**Comment by jayzes** [comment]
Hi @betsythefc - thanks for the note! Unfortunately, we're not yet in compliance with the F-Droid [Inclusion Policy](https://f-droid.org/wiki/page/Inclusion_Policy), so we think we would likely not be accepted. We're working that direction though (in particular, working to open-source the underlying webapp that this wraps), and at that point we'd definitely look into F-Droid further.
