### ISSUE TITLE
Exit Application

### ISSUE THREAD

**Issue by elpoisterio** [ello/ello-android#8]
When there is no Internet connection, then on back press  application should exit.

**Comment by steam** [comment]
Thanks for filing the issue @elpoisterio :metal:

**Comment by elpoisterio** [comment]
Are we allowed to generate a pull request ?

**Comment by steam** [comment]
Yes, we'd love to receive pull requests. In some cases we may not accept them if they are not inline with our product roadmap. Thanks for the interest and for the help. We really appreciate it.

**Comment by steam** [comment]
Fixed in #11
